root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/meuprimeirocrudgo ."
  bin = "./tmp/meuprimeirocrudgo"
  full_bin = "./tmp/meuprimeirocrudgo"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  poll = true
  poll_interval = 500

[log]
  time = false

[misc]
  clean_on_exit = true
