FROM golang:1.26.4

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest


COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

CMD ["air", "-c", ".air.toml"]
