version: "3.8"

services:
  meuprimeirocrudgo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ORACLE_URL: ${ORACLE_URL}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      oracle:
        condition: service_healthy

  oracle:
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
